In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Student_drop_out_system.csv')
df.head()

,Age,Gender,Home Language,Father Occupation,Mother Occupation,Number Of Siblings,Father Education,Mother Education,School Distance,Means to school,...,English,Math,Science,History,Social Science,Religious Study,Family Annual income,Extra Tution,Hours of study per day,Class Label
0,13-15 years,female,Native Language,Immigrant,Home maker,Four or more,secondary,secondary,1-2 km,Rickshaw,...,67,35,42,35,25,29,300000,Yes,1 hours,Yes
1,10-13 years,male,Bangla,Freelancer,Home maker,Three Children,Honors/ Equivalent,secondary,0.5-1 km,Bicycle/motorbike,...,92,47,50,54,56,91,850000,Yes,3 hours,No
2,13-15 years,female,Native Language,Private sector,Home maker,Three Children,primary,secondary,>7 km,Rickshaw,...,60,81,90,43,81,31,100000,No,3 hours,No
3,13-15 years,female,Bangla,Public sector,Freelancer,Three Children,primary,secondary,0-0.5 km,Walk,...,20,83,54,50,20,82,200000,Yes,1 hours,Yes
4,10-13 years,male,Native Language,Public sector,Home maker,None,Honors/ Equivalent,primary,1-2 km,Walk,...,46,52,32,33,28,81,150000,No,1 hours,Yes

In [3]:
import random as r

In [6]:
df['Class Label']=r.choices(['Yes','No'],weights=(8,6),k=248)

In [7]:
df.head()

,Age,Gender,Home Language,Father Occupation,Mother Occupation,Number Of Siblings,Father Education,Mother Education,School Distance,Means to school,...,English,Math,Science,History,Social Science,Religious Study,Family Annual income,Extra Tution,Hours of study per day,Class Label
0,13-15 years,female,Native Language,Immigrant,Home maker,Four or more,secondary,secondary,1-2 km,Rickshaw,...,67,35,42,35,25,29,300000,Yes,1 hours,No
1,10-13 years,male,Bangla,Freelancer,Home maker,Three Children,Honors/ Equivalent,secondary,0.5-1 km,Bicycle/motorbike,...,92,47,50,54,56,91,850000,Yes,3 hours,Yes
2,13-15 years,female,Native Language,Private sector,Home maker,Three Children,primary,secondary,>7 km,Rickshaw,...,60,81,90,43,81,31,100000,No,3 hours,No
3,13-15 years,female,Bangla,Public sector,Freelancer,Three Children,primary,secondary,0-0.5 km,Walk,...,20,83,54,50,20,82,200000,Yes,1 hours,Yes
4,10-13 years,male,Native Language,Public sector,Home maker,None,Honors/ Equivalent,primary,1-2 km,Walk,...,46,52,32,33,28,81,150000,No,1 hours,No

In [8]:
df.to_csv('test_sdos.csv')

In [9]:
df_old=pd.read_csv('Student_drop_out_system.csv')

In [10]:
df_old

,Age,Gender,Home Language,Father Occupation,Mother Occupation,Number Of Siblings,Father Education,Mother Education,School Distance,Means to school,...,English,Math,Science,History,Social Science,Religious Study,Family Annual income,Extra Tution,Hours of study per day,Class Label
0,13-15 years,female,Native Language,Immigrant,Home maker,Four or more,secondary,secondary,1-2 km,Rickshaw,...,67,35,42,35,25,29,300000,Yes,1 hours,Yes
1,10-13 years,male,Bangla,Freelancer,Home maker,Three Children,Honors/ Equivalent,secondary,0.5-1 km,Bicycle/motorbike,...,92,47,50,54,56,91,850000,Yes,3 hours,No
2,13-15 years,female,Native Language,Private sector,Home maker,Three Children,primary,secondary,>7 km,Rickshaw,...,60,81,90,43,81,31,100000,No,3 hours,No
3,13-15 years,female,Bangla,Public sector,Freelancer,Three Children,primary,secondary,0-0.5 km,Walk,...,20,83,54,50,20,82,200000,Yes,1 hours,Yes
4,10-13 years,male,Native Language,Public sector,Home maker,None,Honors/ Equivalent,primary,1-2 km,Walk,...,46,52,32,33,28,81,150000,No,1 hours,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,13-15 years,female,Native Language,Private sector,Home maker,Four or more,primary,secondary,6-7 km,Walk,...,34,66,86,59,86,85,250000,Yes,3 hours,No
244,10-13 years,male,Bangla,Public sector,Home maker,Three Children,primary,secondary,6-7 km,School Bus/Bus,...,80,88,70,27,69,31,800000,Yes,2 hours,No
245,10-13 years,female,Native Language,Private sector,Business,Three Children,primary,None,0-0.5 km,Walk,...,31,85,28,38,31,52,200000,Yes,1 hours,Yes
246,13-15 years,female,Bangla,Private sector,Home maker,None,secondary,secondary,1-2 km,School Bus/Bus,...,56,80,42,67,76,30,350000,Yes,2 hours,No
247,10-13 years,female,Native Language,Private sector,Home maker,Three Children,secondary,None,1-2 km,School Bus/Bus,...,75,79,87,87,55,45,850000,Yes,3 hours,No

In [11]:
df.head()

,Age,Gender,Home Language,Father Occupation,Mother Occupation,Number Of Siblings,Father Education,Mother Education,School Distance,Means to school,...,English,Math,Science,History,Social Science,Religious Study,Family Annual income,Extra Tution,Hours of study per day,Class Label
0,13-15 years,female,Native Language,Immigrant,Home maker,Four or more,secondary,secondary,1-2 km,Rickshaw,...,67,35,42,35,25,29,300000,Yes,1 hours,No
1,10-13 years,male,Bangla,Freelancer,Home maker,Three Children,Honors/ Equivalent,secondary,0.5-1 km,Bicycle/motorbike,...,92,47,50,54,56,91,850000,Yes,3 hours,Yes
2,13-15 years,female,Native Language,Private sector,Home maker,Three Children,primary,secondary,>7 km,Rickshaw,...,60,81,90,43,81,31,100000,No,3 hours,No
3,13-15 years,female,Bangla,Public sector,Freelancer,Three Children,primary,secondary,0-0.5 km,Walk,...,20,83,54,50,20,82,200000,Yes,1 hours,Yes
4,10-13 years,male,Native Language,Public sector,Home maker,None,Honors/ Equivalent,primary,1-2 km,Walk,...,46,52,32,33,28,81,150000,No,1 hours,No

In [20]:
add_df=df.iloc[:50,:]
add_df

,Age,Gender,Home Language,Father Occupation,Mother Occupation,Number Of Siblings,Father Education,Mother Education,School Distance,Means to school,...,English,Math,Science,History,Social Science,Religious Study,Family Annual income,Extra Tution,Hours of study per day,Class Label
0,13-15 years,female,Native Language,Immigrant,Home maker,Four or more,secondary,secondary,1-2 km,Rickshaw,...,67,35,42,35,25,29,300000,Yes,1 hours,No
1,10-13 years,male,Bangla,Freelancer,Home maker,Three Children,Honors/ Equivalent,secondary,0.5-1 km,Bicycle/motorbike,...,92,47,50,54,56,91,850000,Yes,3 hours,Yes
2,13-15 years,female,Native Language,Private sector,Home maker,Three Children,primary,secondary,>7 km,Rickshaw,...,60,81,90,43,81,31,100000,No,3 hours,No
3,13-15 years,female,Bangla,Public sector,Freelancer,Three Children,primary,secondary,0-0.5 km,Walk,...,20,83,54,50,20,82,200000,Yes,1 hours,Yes
4,10-13 years,male,Native Language,Public sector,Home maker,None,Honors/ Equivalent,primary,1-2 km,Walk,...,46,52,32,33,28,81,150000,No,1 hours,No
5,10-13 years,male,Bangla,Unemployed,Home maker,None,Honors/ Equivalent,Honors/Equivalent,0.5-1 km,Walk,...,24,43,49,56,60,47,180000,No,1 hours,Yes
6,10-13 years,female,Native Language,Private sector,Home maker,None,secondary,secondary,0.5-1 km,Bicycle/motorbike,...,86,79,59,63,26,62,500000,Yes,2 hours,No
7,13-15 years,female,Bangla,Worker,Home maker,Four or more,Masters/ Equivalent and above,Honors/Equivalent,0.5-1 km,Walk,...,61,24,67,75,66,56,250000,Yes,2 hours,Yes
8,10-13 years,male,Native Language,Private sector,Agriculture,Two Children,primary,Honors/Equivalent,1-2 km,Bicycle/motorbike,...,20,62,27,82,29,30,180000,No,1 hours,Yes
9,10-13 years,female,Native Language,Private sector,Home maker,Three Children,secondary,secondary,1-2 km,Rickshaw,...,35,63,53,68,92,54,700000,Yes,2 hours,Yes
10,13-15 years,male,Native Language,Worker,Private sector,Two Children,Honors/ Equivalent,secondary,0-0.5 km,Bicycle/motorbike,...,21,92,43,71,76,71,400000,Yes,3 hours,Yes
11,13-15 years,male,Bangla,Private sector,Home maker,Three Children,primary,secondary,0-0.5 km,Rickshaw,...,40,53,73,87,84,44,500000,Yes,2 hours,No
12,15-18 years,male,Native Language,Agriculture,Home maker,None,Honors/ Equivalent,secondary,4-5 km,Rickshaw,...,90,25,25,90,80,22,250000,Yes,2 hours,Yes
13,13-15 years,female,English,Worker,Home maker,None,secondary,secondary,6-7 km,School Bus/Bus,...,52,81,50,23,72,85,900000,Yes,3 hours,Yes
14,10-13 years,female,Native Language,Private sector,Home maker,Two Children,Masters/ Equivalent and above,secondary,6-7 km,Walk,...,78,75,86,75,37,88,200000,Yes,3 hours,Yes
15,10-13 years,female,Native Language,Immigrant,Business,Three Children,primary,secondary,0-0.5 km,School Bus/Bus,...,67,45,49,62,70,89,800000,Yes,3 hours,Yes
16,13-15 years,male,Bangla,Agriculture,Home maker,Three Children,primary,secondary,0-0.5 km,Rickshaw,...,48,77,32,30,87,87,700000,Yes,2 hours,No
17,10-13 years,male,Native Language,Private sector,Home maker,None,primary,secondary,>7 km,Bicycle/motorbike,...,36,41,78,56,22,27,300000,Yes,1 hours,No
18,13-15 years,female,Native Language,Agriculture,Home maker,None,primary,secondary,0-0.5 km,Bicycle/motorbike,...,87,38,28,28,36,47,180000,No,1 hours,Yes
19,10-13 years,female,Native Language,Private sector,Home maker,Four or more,primary,secondary,4-5 km,School Bus/Bus,...,65,44,83,41,29,87,200000,Yes,2 hours,No
20,13-15 years,female,Native Language,Business,Home maker,None,primary,None,1-2 km,Walk,...,88,44,48,65,47,60,550000,Yes,2 hours,No
21,15-18 years,male,Native Language,Immigrant,Home maker,Two Children,Honors/ Equivalent,secondary,0-0.5 km,Private car,...,53,41,40,71,57,87,100000,No,2 hours,No
22,10-13 years,male,Bangla,Unemployed,Home maker,None,secondary,None,6-7 km,Walk,...,69,49,49,88,26,91,250000,Yes,2 hours,No
23,15-18 years,male,Bangla,Private sector,Home maker,Four or more,Honors/ Equivalent,None,6-7 km,Walk,...,66,88,28,87,28,81,900000,Yes,2 hours,No
24,above 18 years,female,Bangla,Worker,Business,Three Children,secondary,secondary,4-5 km,Bicycle/motorbike,...,27,45,71,51,28,56,250000,Yes,2 hours,No
25,10-13 years,female,Native Language,Public sector,Home maker,Four or more,primary,primary,2-3 km,Rickshaw,...,60,31,89,32,21,35,100000,No,2 hours,No
26,13-15 years,female,Bangla,Agriculture,Business,Two Children,primary,secondary,0-0.5 km,Rickshaw,...,65,55,41,77,33,78,100000,No,2 hours,Yes
27,13-15 years,male,Native Language,Agriculture,Home maker,Two Children,primary,secondary,0-0.5 km,School Bus/Bus,...,78,69,36,61,89,48,150000,No,2 hours,Yes
28,13-15 years,female,Native Language,Freelancer,Home maker,Two Children,secondary,secondary,6-7 km,Bicycle/motorbike,...,47,88,88,56,51,55,250000,Yes,3 hours,No
29,10-13 years,female,Bangla,Public sector,Worker,None,primary,secondary,4-5 km,School Bus/Bus,...,49,89,86,87,20,87,400000,Yes,3 hours,Yes
30,10-13 years,female,Bangla,Freelancer,Immigrant,Four or more,secondary,secondary,1-2 km,Private car,...,66,73,74,36,42,84,650000,Yes,3 hours,Yes
31,10-13 years,female,Native Language,Immigrant,Home maker,Three Children,primary,secondary,2-3 km,School Bus/Bus,...,57,82,30,71,21,42,300000,Yes,1 hours,No
32,10-13 years,female,Bangla,Immigrant,Home maker,Two Children,primary,secondary,6-7 km,School Bus/Bus,...,77,83,49,29,24,48,250000,Yes,2 hours,No
33,13-15 years,male,Bangla,Private sector,Home maker,Two Children,primary,secondary,6-7 km,Walk,...,53,20,88,64,34,41,300000,Yes,2 hours,No
34,15-18 years,male,Native Language,Freelancer,Home maker,Two Children,primary,secondary,0.5-1 km,Rickshaw,...,26,83,29,91,27,52,150000,No,2 hours,No
35,13-15 years,male,Native Language,Private sector,Worker,Three Children,Honors/ Equivalent,None,4-5 km,Rickshaw,...,40,55,59,45,32,47,800000,Yes,2 hours,Yes
36,10-13 years,male,Bangla,Immigrant,Immigrant,None,primary,primary,0-0.5 km,School Bus/Bus,...,65,46,58,26,36,26,300000,Yes,1 hours,Yes
37,13-15 years,female,Bangla,Public sector,Public sector,None,secondary,None,1-2 km,Walk,...,82,89,33,78,56,32,200000,Yes,3 hours,Yes
38,10-13 years,male,Native Language,Worker,Home maker,None,None,None,0-0.5 km,School Bus/Bus,...,84,84,43,78,61,68,650000,Yes,above 3 hours,Yes
39,13-15 years,male,Native Language,Public sector,Worker,None,primary,secondary,1-2 km,Private car,...,41,51,81,48,51,34,650000,Yes,2 hours,Yes
40,13-15 years,female,Native Language,Immigrant,Immigrant,None,primary,primary,2-3 km,Walk,...,80,55,53,22,29,74,900000,Yes,2 hours,Yes
41,10-13 years,male,Native Language,Worker,Home maker,None,secondary,secondary,>7 km,Rickshaw,...,41,20,73,76,59,24,200000,Yes,2 hours,No
42,13-15 years,male,Native Language,Immigrant,Home maker,Four or more,None,Honors/Equivalent,>7 km,Private car,...,87,73,59,62,46,48,100000,No,2 hours,Yes
43,15-18 years,female,English,Freelancer,Home maker,Two Children,secondary,secondary,1-2 km,School Bus/Bus,...,71,65,66,42,50,82,900000,Yes,3 hours,Yes
44,13-15 years,female,Native Language,Private sector,Home maker,Two Children,Honors/ Equivalent,secondary,0.5-1 km,Walk,...,49,34,21,74,78,31,700000,Yes,2 hours,No
45,13-15 years,male,Bangla,Immigrant,Business,Four or more,None,primary,2-3 km,School Bus/Bus,...,85,53,71,54,51,80,700000,Yes,3 hours,Yes
46,13-15 years,female,Bangla,Business,Home maker,Four or more,primary,secondary,2-3 km,School Bus/Bus,...,77,20,32,77,85,86,300000,Yes,3 hours,Yes
47,13-15 years,male,Bangla,Worker,Agriculture,Three Children,primary,Honors/Equivalent,0-0.5 km,Walk,...,46,27,35,81,76,30,150000,No,1 hours,No
48,10-13 years,male,English,Private sector,Home maker,Three Children,secondary,secondary,1-2 km,Rickshaw,...,52,50,35,85,35,22,600000,Yes,2 hours,No
49,13-15 years,female,Bangla,Private sector,Home maker,Three Children,secondary,secondary,4-5 km,Bicycle/motorbike,...,67,83,48,33,89,40,400000,Yes,3 hours,Yes

In [21]:
add_df.shape

(50, 28)

In [22]:
df_old.shape

(248, 28)

In [25]:
final_df=df_old.append(add_df)

In [24]:
df_old

,Age,Gender,Home Language,Father Occupation,Mother Occupation,Number Of Siblings,Father Education,Mother Education,School Distance,Means to school,...,English,Math,Science,History,Social Science,Religious Study,Family Annual income,Extra Tution,Hours of study per day,Class Label
0,13-15 years,female,Native Language,Immigrant,Home maker,Four or more,secondary,secondary,1-2 km,Rickshaw,...,67,35,42,35,25,29,300000,Yes,1 hours,Yes
1,10-13 years,male,Bangla,Freelancer,Home maker,Three Children,Honors/ Equivalent,secondary,0.5-1 km,Bicycle/motorbike,...,92,47,50,54,56,91,850000,Yes,3 hours,No
2,13-15 years,female,Native Language,Private sector,Home maker,Three Children,primary,secondary,>7 km,Rickshaw,...,60,81,90,43,81,31,100000,No,3 hours,No
3,13-15 years,female,Bangla,Public sector,Freelancer,Three Children,primary,secondary,0-0.5 km,Walk,...,20,83,54,50,20,82,200000,Yes,1 hours,Yes
4,10-13 years,male,Native Language,Public sector,Home maker,None,Honors/ Equivalent,primary,1-2 km,Walk,...,46,52,32,33,28,81,150000,No,1 hours,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,13-15 years,female,Native Language,Private sector,Home maker,Four or more,primary,secondary,6-7 km,Walk,...,34,66,86,59,86,85,250000,Yes,3 hours,No
244,10-13 years,male,Bangla,Public sector,Home maker,Three Children,primary,secondary,6-7 km,School Bus/Bus,...,80,88,70,27,69,31,800000,Yes,2 hours,No
245,10-13 years,female,Native Language,Private sector,Business,Three Children,primary,None,0-0.5 km,Walk,...,31,85,28,38,31,52,200000,Yes,1 hours,Yes
246,13-15 years,female,Bangla,Private sector,Home maker,None,secondary,secondary,1-2 km,School Bus/Bus,...,56,80,42,67,76,30,350000,Yes,2 hours,No
247,10-13 years,female,Native Language,Private sector,Home maker,Three Children,secondary,None,1-2 km,School Bus/Bus,...,75,79,87,87,55,45,850000,Yes,3 hours,No

In [26]:
final_df.shape

(298, 28)

In [27]:
final_df.to_csv('improvedSDOS.csv')